blueprint:
  name: Motion-Activated Light Switch except 
  description: Turn on a light switch when motion is detected and turn it off when no motion is detected for a specified amount of time.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that will trigger the light switch.
      selector:
        entity:
          domain: binary_sensor
    light_switch:
      name: Light Switch
      description: The light switch that will be controlled by the motion sensor.
      selector:
        entity:
          domain: switch
    delay_seconds:
      name: Delay (secods)
      description: The number of seconds to wait after the last detected motion before turning off the light.
      default: 30
      selector:
        number:
          min: 0
          max: 600
          step: 5
  source_url: https://github.com/p-borat/ha_1/edit/main/condition-2.yaml

mode: restart

trigger:
  platform: state
  entity_id: !input motion_sensor
  to: 'on'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_switch
            state: 'off'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input light_switch
      - conditions:
          - condition: state
            entity_id: !input light_switch
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input motion_sensor

  - alias: 'Turn off light when no motion detected'
    trigger:
      platform: state
      entity_id: !input motion_sensor
      to: 'off'
      for:
        seconds: !input delay_seconds
    condition:
      - condition: state
        entity_id: !input light_switch
        state: 'on'
    action:
      - service: switch.turn_off
        target:
          entity_id: !input light_switch
